import React, { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    appName: "SNM Health Monitor",
    navDashboard: "Dashboard",
    navWorkouts: "Workouts",
    navNutrition: "Nutrition",
    navProfile: "Profile",
    navLibrary: "Library",
    navAdmin: "Admin",
    navLogout: "Logout",
    navLanguage: "Language",
    navTheme: "Theme",
    langEnglish: "English",
    langTamil: "தமிழ்",
    themeSystem: "Device",
    themeLight: "Light",
    themeDark: "Dark",
    loginTitle: "Welcome back",
    loginSubtitle: "Log in to keep your fitness streak alive.",
    loginEmail: "Email",
    loginPassword: "Password",
    loginButton: "Log in",
    loginOr: "Or continue with",
    loginCreate: "Create an account",
    loginForgot: "Forgot password?",
    loginFailed: "Login failed",
    registerTitle: "Start your journey",
    registerSubtitle: "Build habits, track progress, and hit your goals.",
    registerName: "Name",
    registerButton: "Create account",
    registerHaveAccount: "Already have an account?",
    registerLogin: "Log in",
    verifyTitle: "Verify Email",
    verifyWorking: "Verifying your email...",
    verifySuccess: "Email verified. You can log in now.",
    verifyFailed: "Verification failed.",
    verifyMissing: "Verification link is missing.",
    verifyBackLogin: "Back to login",
    verifyResend: "Resend verification",
    verifyResent: "Verification email sent.",
    verifyResendFailed: "Failed to resend verification email.",
    forgotTitle: "Forgot password",
    forgotSubtitle: "We will email you a 6-digit reset code.",
    forgotSend: "Send reset code",
    forgotHint:
      "OTP email-ku vandhucha? Code-ai enter pannitu new password update panna reset page-ku pogalaam.",
    forgotGoReset: "Go to reset password",
    forgotRemembered: "Remembered?",
    forgotBackLogin: "Back to login",
    resetTitle: "Reset password",
    resetSubtitle: "Enter the code sent to your email.",
    resetOtp: "6-digit code",
    resetNewPassword: "New password",
    resetUpdate: "Update password",
    dashboardWelcome: "Welcome, {name}",
    dashboardSubtitle: "Track your training, nutrition, and body metrics in one place.",
    statWorkoutsLogged: "Workouts logged",
    statCaloriesBurned: "Calories burned",
    statCaloriesConsumed: "Calories consumed",
    statCurrentStreak: "Current streak (days)",
    statBestStreak: "Best streak (days)",
    statLatestHeartRate: "Latest heart rate (bpm)",
    weeklyReportTitle: "Weekly Progress Report",
    weeklyReportSince: "Since {date}.",
    weeklyWorkouts: "Workouts this week",
    weeklyWater: "Water (ml)",
    weeklyHeartRate: "Avg heart rate (bpm)",
    chartWeeklyCalories: "Weekly Calories",
    chartWeeklyConsumed: "Weekly Calories Consumed",
    chartWeeklyWater: "Weekly Water Intake",
    chartWeeklyHeartRate: "Weekly Heart Rate",
    chartWeightTrend: "Weight Trend",
    chartEnergyBalance: "Energy Balance",
    chartHydrationRecovery: "Hydration vs Recovery",
    chartNetCalories: "Net calories",
    chartToggleBurned: "Burned",
    chartToggleConsumed: "Consumed",
    chartToggleWater: "Water",
    chartToggleHeart: "Heart rate",
    chartDownloadCsv: "Download CSV",
    chartBestWeek: "Best week",
    chartWorstWeek: "Needs attention",
    chartDataRange: "Last 4 weeks of data",
    dietTitle: "Nutrition & Calories",
    dietSubtitle: "Balance calories consumed with calories burned.",
    dietMealLog: "Meal Log",
    dietNoMeals: "No meals logged yet.",
    dietHydration: "Hydration Tracker",
    dietHydrationSubtitle: "Log every glass to keep your hydration streak alive.",
    dietWaterToday: "Water today (ml)",
    dietWaterLogged: "Water logged (ml)",
    dietWaterLog: "Water Log",
    dietNoWater: "No water entries yet.",
    dietDelete: "Delete",
    dietBalance: "Balance",
    dietHydrationEntry: "Hydration entry",
    workoutsTitle: "Workout Tracker",
    workoutsSubtitle: "Log every session to see your momentum.",
    workoutsRecent: "Recent Workouts",
    workoutsNone: "No workouts yet.",
    libraryTitle: "Exercise Library",
    librarySubtitle: "Browse simple exercises to build your plan.",
    libraryListTitle: "Exercise List",
    libraryEmpty: "No exercises in this focus.",
    libraryWatchVideo: "Watch video",
    libraryVideoUnavailable: "Video unavailable",
    libraryFocusLabel: "Focus",
    "libraryFilter.All": "All",
    "libraryFilter.FullBody": "Full body",
    "libraryFilter.UpperBody": "Upper body",
    "libraryFilter.LowerBody": "Lower body",
    "libraryFilter.Core": "Core",
    "libraryFilter.Cardio": "Cardio / HIIT",
    "libraryFilter.Mobility": "Mobility",
    libraryCategoryLabel: "Category",
    "libraryCategory.All": "All",
    "libraryCategory.Strength": "Strength",
    "libraryCategory.Cardio": "Cardio",
    "libraryCategory.HIIT": "HIIT",
    "libraryCategory.Core": "Core",
    "libraryCategory.Mobility": "Mobility",
    heartRateTitle: "Heart Rate Tracker",
    heartRateSubtitle: "Log pulse readings to monitor your recovery.",
    heartRateLog: "Heart Rate Log",
    heartRateEntry: "Pulse reading",
    heartRateNone: "No heart rate entries yet.",
    adminTitle: "Admin Control Center",
    adminSubtitle: "Monitor user activity and app usage.",
    adminUsers: "Users",
    adminWorkouts: "Workouts",
    adminMeals: "Meals",
    adminWaterEntries: "Water entries",
    adminHeartRateEntries: "Heart rate entries",
    adminSmtpTitle: "SMTP Settings",
    adminSmtpSubtitle: "Used for sending OTP reset codes.",
    adminSmtpHost: "SMTP host",
    adminSmtpPort: "Port",
    adminSmtpUser: "SMTP user",
    adminSmtpPass: "SMTP password",
    adminSmtpFrom: "From name <email>",
    adminSmtpTest: "Test email (optional)",
    adminSmtpSave: "Save SMTP Settings",
    adminSmtpSend: "Send Test Email",
    adminExportTitle: "Analytics Exports",
    adminExportSubtitle: "Download CSV or PDF snapshots of platform activity.",
    adminExportCsv: "Download CSV",
    adminExportPdf: "Download PDF",
    adminExportFailed: "Failed to download analytics report.",
    adminLogsTitle: "Security Logs",
    adminLogsSubtitle: "Latest account and admin activity.",
    adminLogsEmpty: "No log entries yet.",
    adminLogsDelete: "Clear",
    adminLogsDeleteFailed: "Failed to delete log entry.",
    adminAccessOnly: "Admin Access Only",
    adminAccessHint: "You need admin permissions to view this page.",
    adminNoUsers: "No users found.",
    profileTitle: "Your Profile",
    profileSubtitle: "Update your stats and goals anytime.",
    profileAge: "Age",
    profileHeight: "Height (cm)",
    profileWeight: "Weight (kg)",
    profileGoals: "Goals",
    profileTargetWeight: "Target weight (kg)",
    profileWeeklyWorkouts: "Weekly workouts",
    profileDailyCalories: "Daily calorie target",
    profileDailyWater: "Daily water goal (ml)",
    profileSave: "Save Profile",
    profilePasswordTitle: "Update Password",
    profilePasswordHint:
      "8-16 chars, at least 1 uppercase, 1 lowercase, 1 number, 1 special character.",
    profileCurrentPassword: "Current password",
    profileNewPassword: "New password",
    profileConfirmPassword: "Confirm new password",
    profileUpdatePassword: "Update Password",
    profileAgeGuidance: "Age-Specific Guidance",
    profileAgeHint: "This is a general reference chart. For medical advice, consult a professional.",
    profileAgeBand: "Age Band",
    profileBmiRange: "BMI Range",
    profileIdealRange: "Ideal Weight Range",
    profileTargetBmi: "Target BMI",
    profileTargetWeightSingle: "Target Weight (for your height)",
    profileAgeBandHint: "Based on your age entry.",
    profileTargetBmiHint: "Midpoint BMI for your age band.",
    profileTargetWeightHint: "Calculated from your height.",
    profileGoalPlan: "Goal Plan",
    profileGoalHint: "Choose your goal and activity level to get a detailed plan.",
    profileGoalLoss: "Weight loss",
    profileGoalMaintain: "Maintain weight",
    profileGoalGain: "Weight gain",
    profileActivitySedentary: "Sedentary (little/no exercise)",
    profileActivityLight: "Light (1-3 days/week)",
    profileActivityModerate: "Moderate (3-5 days/week)",
    profileActivityActive: "Active (6-7 days/week)",
    profileActivityVeryActive: "Very active (twice daily)",
    profileBmr: "BMR",
    profileTdee: "TDEE",
    profileTargetCalories: "Target Calories",
    profileWaterTarget: "Daily Water Target",
    profileWorkoutGuidance: "Workout Guidance",
    reminderTitle: "Workout Reminder",
    reminderSubtitle: "Set your workout schedule and time.",
    reminderEnable: "Enable reminders",
    reminderChannelLabel: "Delivery channels",
    reminderChannelsHint: "Pick at least one channel. SMS needs your phone number with country code.",
    reminderChannelEmail: "Email",
    reminderChannelSms: "SMS",
    reminderPhone: "SMS phone number (+CountryCode)",
    reminderCountryCode: "Country code",
    reminderPhoneNumber: "Phone number",
    reminderPhoneHint: "Example: +919876543210",
    reminderPhoneInvalid: "Enter a valid phone number for the selected country.",
    reminderStartDate: "Start sending from",
    reminderStartDateHint: "Reminders won't fire before this date.",
    reminderQuietHours: "Quiet hours",
    reminderQuietHoursHint: "Mute reminders between these times in your timezone.",
    reminderQuietStart: "Quiet hours start",
    reminderQuietEnd: "Quiet hours end",
    reminderSave: "Save reminder",
    reminderSaved: "Reminder saved",
    reminderFailed: "Failed to save reminder",
    reminderValidation: "Select days, time, and at least one channel.",
    reminderSmsValidation: "Add a valid phone number for SMS reminders.",
    reminderQuietValidation: "Provide start and end time for quiet hours.",
    weeklyMealTitle: "Weekly Meal Plan",
    weeklyMealSubtitle: "Rotating meals with limited repeats each week.",
    "meal.breakfast": "Breakfast",
    "meal.lunch": "Lunch",
    "meal.snack": "Snack",
    "meal.dinner": "Dinner",
    mealColFood: "Food",
    mealColAmount: "Amount",
    mealColCalories: "Calories",
    dayMon: "Monday",
    dayTue: "Tuesday",
    dayWed: "Wednesday",
    dayThu: "Thursday",
    dayFri: "Friday",
    daySat: "Saturday",
    daySun: "Sunday",
    gainFoodWaterHint: "Water target: {amount} ml per day.",
    gainFoodRice: "Cooked rice (1 cup)",
    gainFoodOats: "Oats (40g)",
    gainFoodEggs: "Eggs (2)",
    gainFoodChicken: "Chicken (150g)",
    gainFoodPaneer: "Paneer (100g)",
    gainFoodNuts: "Mixed nuts (30g)",
    gainFoodBanana: "Banana (1)",
    gainFoodMilk: "Milk (250ml)",
    gainFoodVeg: "Mixed vegetables (1 cup)",
    gainFoodIdli: "Idli (3)",
    gainFoodSambar: "Sambar (1 cup)",
    gainFoodPoha: "Poha (1 bowl)",
    gainFoodUpma: "Upma (1 bowl)",
    gainFoodDosa: "Dosa (2)",
    gainFoodRoti: "Roti (2)",
    gainFoodFish: "Fish (150g)",
    gainFoodRajma: "Rajma (1 cup)",
    gainFoodYogurt: "Yogurt (200ml)",
    gainFoodFruitBowl: "Fruit bowl (1)",
    gainFoodPeanutButter: "Peanut butter (2 tbsp)",
    gainFoodBread: "Whole wheat bread (2)",
    "reminderDay.0": "Sun",
    "reminderDay.1": "Mon",
    "reminderDay.2": "Tue",
    "reminderDay.3": "Wed",
    "reminderDay.4": "Thu",
    "reminderDay.5": "Fri",
    "reminderDay.6": "Sat",
    formFoodItem: "Food item",
    formCalories: "Calories",
    formDate: "Date",
    formAddMeal: "Add Meal",
    formFoodSuggestions: "You can type manually or pick from suggestions.",
    formWaterMl: "Water (ml)",
    formAddWater: "Add Water",
    formWorkoutType: "Workout type",
    formWorkoutMinutes: "Minutes",
    formAddWorkout: "Add Workout",
    formHeartRate: "Heart rate (bpm)",
    formAddHeartRate: "Add Heart Rate",
    suggestionIdli: "Idli",
    suggestionDosa: "Dosa",
    suggestionRice: "Cooked rice",
    suggestionChicken: "Chicken",
    suggestionPaneer: "Paneer",
    suggestionEggs: "Eggs",
    suggestionOats: "Oats",
    suggestionFruit: "Fruit bowl",
    suggestionMilk: "Milk",
    suggestionYogurt: "Yogurt",
    suggestionNuts: "Mixed nuts",
    suggestionPoha: "Poha",
    suggestionUpma: "Upma",
    suggestionSambar: "Sambar",
    suggestionFish: "Fish",
    suggestionRajma: "Rajma",
    suggestionSalad: "Salad",
    categoryCardio: "Cardio",
    categoryStrength: "Strength",
    categoryYoga: "Yoga",
    categoryHIIT: "HIIT",
    categoryMobility: "Mobility",
    categoryOther: "Other",
    loading: "Loading...",
    adminDelete: "Delete",
    profileBmi: "BMI",
    profileGenderMale: "Male",
    profileGenderFemale: "Female",
    profileGenderOther: "Other",
    planWeekA: "Week Plan A",
    planWeekB: "Week Plan B",
    planLossFocusA: "3 strength sessions + 2 cardio sessions",
    planLossSessionsA: "Mon Upper, Tue Cardio, Thu Lower, Fri Cardio, Sat Full body",
    planLossNutritionA: "Keep a steady calorie deficit with high protein and vegetables.",
    planLossHydrationA: "Hydrate throughout the day; aim for the water target shown.",
    planLossFocusB: "4 strength sessions + 1 HIIT",
    planLossSessionsB: "Mon Upper, Tue Lower, Thu Push, Fri Pull, Sat HIIT",
    planLossNutritionB: "Carb intake around workouts, protein every meal.",
    planLossHydrationB: "Add 500 ml on training days if you sweat a lot.",
    planGainFocusA: "4-5 strength sessions + 1 light cardio",
    planGainSessionsA: "Mon Push, Tue Pull, Thu Legs, Fri Upper, Sat Light cardio",
    planGainNutritionA: "Calorie surplus with protein and complex carbs.",
    planGainHydrationA: "Hit the water target and add 250-500 ml on heavy days.",
    planGainFocusB: "Upper/Lower split with volume focus",
    planGainSessionsB: "Mon Upper, Tue Lower, Thu Upper, Fri Lower, Sat Optional arms",
    planGainNutritionB: "Spread calories across 4-5 meals; include healthy fats.",
    planGainHydrationB: "Consistent intake; avoid long gaps without water.",
    planGuidanceLoss:
      "Focus on strength 3-4 days/week + 150-300 min/week moderate cardio. Add 1-2 HIIT sessions only if recovery is good.",
    planGuidanceGain:
      "Prioritize strength 4-5 days/week with progressive overload. Keep cardio light-moderate 1-2 days/week.",
    planGuidanceMaintain: "Maintain with 3 days strength + 2-3 days cardio or active recovery.",
    maintainFoodOats: "Oats (40g)",
    maintainFoodFruit: "Fruit (1)",
    maintainFoodRice: "Cooked rice (1 cup)",
    maintainFoodChicken: "Chicken (150g)",
    maintainFoodVeg: "Mixed vegetables (1 cup)",
    maintainFoodNuts: "Mixed nuts (30g)",
    maintainFoodYogurt: "Yogurt (200ml)",
    maintainFoodRoti: "Roti (2)",
    maintainFoodPaneer: "Paneer (100g)",
    maintainFoodIdli: "Idli (3)",
    maintainFoodSambar: "Sambar (1 cup)",
    maintainFoodFish: "Fish (150g)",
    maintainFoodEggs: "Eggs (2)",
    maintainFoodPoha: "Poha (1 bowl)",
    maintainFoodMilk: "Milk (250ml)",
    maintainFoodRajma: "Rajma (1 cup)",
    maintainFoodUpma: "Upma (1 bowl)",
    maintainFoodDosa: "Dosa (2)",
    lossFoodOats: "Oats (40g)",
    lossFoodFruit: "Fruit (1)",
    lossFoodRice: "Cooked rice (1 cup)",
    lossFoodChicken: "Chicken (150g)",
    lossFoodVeg: "Mixed vegetables (1 cup)",
    lossFoodNuts: "Mixed nuts (30g)",
    lossFoodYogurt: "Yogurt (200ml)",
    lossFoodRoti: "Roti (2)",
    lossFoodPaneer: "Paneer (100g)",
    lossFoodIdli: "Idli (3)",
    lossFoodSambar: "Sambar (1 cup)",
    lossFoodFish: "Fish (150g)",
    lossFoodEggs: "Eggs (2)",
    lossFoodPoha: "Poha (1 bowl)",
    lossFoodMilk: "Milk (250ml)",
    lossFoodRajma: "Rajma (1 cup)",
    lossFoodUpma: "Upma (1 bowl)",
    lossFoodDosa: "Dosa (2)",
    assistantTitle: "Coach Chat",
    assistantSubtitle: "Ask about workouts, meals, or app guidance.",
    assistantInputPlaceholder: "Type your question...",
    assistantSend: "Send",
    assistantOpenButton: "Need help?",
    assistantClose: "Close",
    assistantEmpty: "No messages yet. Say hi!",
    assistantWelcome:
      "Hey! I'm your AI coach. Ask me about training plans, nutrition, or anything inside SNM Health Monitor.",
    assistantError: "Couldn't get a response. Please try again.",
    assistantThinking: "Thinking..."
  },
  ta: {
    appName: "SNM Health Monitor",
    navDashboard: "டாஷ்போர்டு",
    navWorkouts: "வொர்க்அவுட்ஸ்",
    navNutrition: "நியூட்ரிஷன்",
    navProfile: "ப்ரோஃபைல்",
    navLibrary: "லைப்ரரி",
    navAdmin: "அட்மின்",
    navLogout: "லாக்அவுட்",
    navLanguage: "மொழி",
    navTheme: "தீம்",
    langEnglish: "English",
    langTamil: "தமிழ்",
    themeSystem: "Device",
    themeLight: "Light",
    themeDark: "Dark",
    loginTitle: "மீண்டும் வரவேற்கிறோம்",
    loginSubtitle: "உங்கள் fitness streak தொடர்ந்து வளர லாகின் செய்யுங்கள்.",
    loginEmail: "மின்னஞ்சல்",
    loginPassword: "கடவுச்சொல்",
    loginButton: "லாகின்",
    loginOr: "அல்லது இதன் மூலம் தொடர்க",
    loginCreate: "புதிய கணக்கு உருவாக்கு",
    loginForgot: "கடவுச்சொல் மறந்துவிட்டதா?",
    loginFailed: "லாகின் தோல்வி",
    registerTitle: "உங்கள் பயணத்தை தொடங்குங்கள்",
    registerSubtitle: "பழக்கங்களை உருவாக்குங்கள், முன்னேற்றத்தை பதிவு செய்யுங்கள்.",
    registerName: "பெயர்",
    registerButton: "கணக்கு உருவாக்கு",
    registerHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    registerLogin: "லாகின்",
    verifyTitle: "மெயில் சரிபார்ப்பு",
    verifyWorking: "மெயிலை சரிபார்க்கிறது...",
    verifySuccess: "மெயில் சரிபார்க்கப்பட்டது. இப்போது லாகின் செய்யலாம்.",
    verifyFailed: "சரிபார்ப்பு தோல்வி.",
    verifyMissing: "சரிபார்ப்பு லிங்க் இல்லை.",
    verifyBackLogin: "லாகின் பக்கத்திற்கு திரும்ப",
    verifyResend: "மீண்டும் சரிபார்ப்பு அனுப்பு",
    verifyResent: "சரிபார்ப்பு மெயில் அனுப்பப்பட்டது.",
    verifyResendFailed: "சரிபார்ப்பு மெயில் அனுப்ப முடியவில்லை.",
    forgotTitle: "கடவுச்சொல் மறந்துவிட்டது",
    forgotSubtitle: "6 இலக்க OTP உங்களுக்கு மெயிலில் வரும்.",
    forgotSend: "OTP அனுப்பு",
    forgotHint:
      "OTP email-ku vandhucha? Code-ai enter pannitu new password update panna reset page-ku pogalaam.",
    forgotGoReset: "Reset page-க்கு செல்",
    forgotRemembered: "நினைவில் வந்துவிட்டதா?",
    forgotBackLogin: "லாகின் பக்கத்திற்கு திரும்ப",
    resetTitle: "கடவுச்சொல் மாற்று",
    resetSubtitle: "மெயிலுக்கு வந்த OTP-ஐ உள்ளிடுங்கள்.",
    resetOtp: "6 இலக்க OTP",
    resetNewPassword: "புதிய கடவுச்சொல்",
    resetUpdate: "கடவுச்சொல் மாற்று",
    dashboardWelcome: "வரவேற்கிறோம், {name}",
    dashboardSubtitle: "Training, nutrition, body metrics அனைத்தையும் ஒரே இடத்தில் track செய்யலாம்.",
    statWorkoutsLogged: "பதிவுசெய்யப்பட்ட வொர்க்அவுட்ஸ்",
    statCaloriesBurned: "எரிந்த கலோரி",
    statCaloriesConsumed: "உண்டு கொண்ட கலோரி",
    statCurrentStreak: "நடப்பு ஸ்ட்ரீக் (நாட்கள்)",
    statBestStreak: "அதிகபட்ச ஸ்ட்ரீக் (நாட்கள்)",
    statLatestHeartRate: "சமீபத்திய துடிப்பு (bpm)",
    weeklyReportTitle: "வாராந்திர முன்னேற்ற அறிக்கை",
    weeklyReportSince: "{date} முதல்.",
    weeklyWorkouts: "இந்த வார வொர்க்அவுட்ஸ்",
    weeklyWater: "தண்ணீர் (ml)",
    weeklyHeartRate: "சராசரி துடிப்பு (bpm)",
    chartWeeklyCalories: "வாராந்திர கலோரி",
    chartWeeklyConsumed: "வாராந்திர உண்ட கலோரி",
    chartWeeklyWater: "வாராந்திர தண்ணீர்",
    chartWeeklyHeartRate: "வாராந்திர துடிப்பு",
    chartWeightTrend: "எடை மாற்றம்",
    chartEnergyBalance: "எனர்ஜி சமநிலை",
    chartHydrationRecovery: "தண்ணீர் vs மீட்பு",
    chartNetCalories: "நெட் கலோரி",
    chartToggleBurned: "எரிந்தது",
    chartToggleConsumed: "உண்டது",
    chartToggleWater: "தண்ணீர்",
    chartToggleHeart: "இதய துடிப்பு",
    chartDownloadCsv: "CSV டவுன்லோடு",
    chartBestWeek: "சிறந்த வாரம்",
    chartWorstWeek: "கவனம் தேவை",
    chartDataRange: "கடைசி 4 வார தரவு",
    dietTitle: "நியூட்ரிஷன் & கலோரி",
    dietSubtitle: "உண்டு கொண்ட கலோரியும் எரிந்த கலோரியும் சமநிலையில் வைத்திருங்கள்.",
    dietMealLog: "உணவு பதிவு",
    dietNoMeals: "இன்னும் எந்த meal பதிவும் இல்லை.",
    dietHydration: "தண்ணீர் டிராக்கர்",
    dietHydrationSubtitle: "Hydration streak காக்க ஒவ்வொரு கப்பையும் பதிவு செய்யுங்கள்.",
    dietWaterToday: "இன்று தண்ணீர் (ml)",
    dietWaterLogged: "மொத்த தண்ணீர் (ml)",
    dietWaterLog: "தண்ணீர் பதிவு",
    dietNoWater: "இன்னும் தண்ணீர் பதிவுகள் இல்லை.",
    dietDelete: "நீக்கு",
    dietBalance: "சமநிலை",
    dietHydrationEntry: "தண்ணீர் பதிவு",
    workoutsTitle: "வொர்க்அவுட் டிராக்கர்",
    workoutsSubtitle: "ஒவ்வொரு செஷனையும் பதிவு செய்து முன்னேற்றத்தைப் பாருங்கள்.",
    workoutsRecent: "சமீபத்திய வொர்க்அவுட்ஸ்",
    workoutsNone: "இன்னும் வொர்க்அவுட்ஸ் இல்லை.",
    libraryTitle: "எக்சர்சைஸ் லைப்ரரி",
    librarySubtitle: "உங்களுக்கு உதவும் எளிய பயிற்சிகளைப் பாருங்கள்.",
    libraryListTitle: "பயிற்சி பட்டியல்",
    libraryEmpty: "இந்த கவனம் பகுதியில் பயிற்சிகள் இல்லை.",
    libraryWatchVideo: "வீடியோ பார்க்க",
    libraryVideoUnavailable: "வீடியோ இல்லை",
    libraryFocusLabel: "கவனம்",
    "libraryFilter.All": "அனைத்தும்",
    "libraryFilter.FullBody": "முழு உடல்",
    "libraryFilter.UpperBody": "மேல் உடல்",
    "libraryFilter.LowerBody": "கீழ் உடல்",
    "libraryFilter.Core": "மையம்",
    "libraryFilter.Cardio": "கார்டியோ / HIIT",
    "libraryFilter.Mobility": "நெகிழ்வு",
    libraryCategoryLabel: "வகை",
    "libraryCategory.All": "அனைத்தும்",
    "libraryCategory.Strength": "வலு பயிற்சி",
    "libraryCategory.Cardio": "கார்டியோ",
    "libraryCategory.HIIT": "HIIT",
    "libraryCategory.Core": "கோர்",
    "libraryCategory.Mobility": "மொபிலிட்டி",
    heartRateTitle: "இதய துடிப்பு டிராக்கர்",
    heartRateSubtitle: "உங்கள் pulse readings-ஐ பதிவு செய்யுங்கள்.",
    heartRateLog: "இதய துடிப்பு பதிவு",
    heartRateEntry: "துடிப்பு பதிவு",
    heartRateNone: "இன்னும் heart rate பதிவுகள் இல்லை.",
    adminTitle: "அட்மின் கட்டுப்பாட்டு மையம்",
    adminSubtitle: "பயனர் செயல்பாட்டை கண்காணிக்கவும்.",
    adminUsers: "பயனர்கள்",
    adminWorkouts: "வொர்க்அவுட்ஸ்",
    adminMeals: "உணவுகள்",
    adminWaterEntries: "தண்ணீர் பதிவுகள்",
    adminHeartRateEntries: "துடிப்பு பதிவுகள்",
    adminSmtpTitle: "SMTP அமைப்புகள்",
    adminSmtpSubtitle: "OTP அனுப்ப பயன்படும்.",
    adminSmtpHost: "SMTP ஹோஸ்ட்",
    adminSmtpPort: "போர்ட்",
    adminSmtpUser: "SMTP பயனர்",
    adminSmtpPass: "SMTP கடவுச்சொல்",
    adminSmtpFrom: "From பெயர் <email>",
    adminSmtpTest: "டெஸ்ட் மெயில் (விருப்பம்)",
    adminSmtpSave: "SMTP சேமிக்கவும்",
    adminSmtpSend: "டெஸ்ட் மெயில் அனுப்பு",
    adminExportTitle: "ஆனலிட்டிக்ஸ் ஏற்றுமதி",
    adminExportSubtitle: "CSV / PDF ஆக செயல்பாட்டு தரவை டவுன்லோடு செய்யுங்கள்.",
    adminExportCsv: "CSV டவுன்லோடு",
    adminExportPdf: "PDF டவுன்லோடு",
    adminExportFailed: "ஆனலிட்டிக்ஸ் ரிப்போர்ட் டவுன்லோடு தோல்வியடைந்தது.",
    adminLogsTitle: "பாதுகாப்பு பதிவுகள்",
    adminLogsSubtitle: "சமீபத்திய கணக்கு / அட்மின் நடவடிக்கைகள்.",
    adminLogsEmpty: "இன்னும் பதிவுகள் இல்லை.",
    adminLogsDelete: "அழி",
    adminLogsDeleteFailed: "பதிவை நீக்க முடியவில்லை.",
    adminAccessOnly: "அட்மின் மட்டும்",
    adminAccessHint: "இந்த பக்கம் பார்க்க அட்மின் அனுமதி வேண்டும்.",
    adminNoUsers: "பயனர்கள் இல்லை.",
    profileTitle: "உங்கள் ப்ரோஃபைல்",
    profileSubtitle: "உங்கள் விவரங்களையும் இலக்குகளையும் புதுப்பிக்கவும்.",
    profileAge: "வயது",
    profileHeight: "உயரம் (cm)",
    profileWeight: "எடை (kg)",
    profileGoals: "இலக்குகள்",
    profileTargetWeight: "இலக்கு எடை (kg)",
    profileWeeklyWorkouts: "வாரத்திற்கு வொர்க்அவுட்ஸ்",
    profileDailyCalories: "தினசரி கலோரி இலக்கு",
    profileDailyWater: "தினசரி தண்ணீர் இலக்கு (ml)",
    profileSave: "ப்ரோஃபைல் சேமிக்கவும்",
    profilePasswordTitle: "கடவுச்சொல் மாற்றம்",
    profilePasswordHint:
      "8-16 எழுத்துகள், 1 பெரிய எழுத்து, 1 சிறிய எழுத்து, 1 எண், 1 சிறப்பு குறி அவசியம்.",
    profileCurrentPassword: "தற்போதைய கடவுச்சொல்",
    profileNewPassword: "புதிய கடவுச்சொல்",
    profileConfirmPassword: "புதிய கடவுச்சொலை உறுதி செய்",
    profileUpdatePassword: "கடவுச்சொல் மாற்று",
    profileAgeGuidance: "வயது சார்ந்த வழிகாட்டல்",
    profileAgeHint: "இது பொதுவான குறிப்புகள்; மருத்துவ ஆலோசனைக்கு நிபுணரை அணுகவும்.",
    profileAgeBand: "வயது பகுதி",
    profileBmiRange: "BMI வரம்பு",
    profileIdealRange: "சரியான எடை வரம்பு",
    profileTargetBmi: "இலக்கு BMI",
    profileTargetWeightSingle: "உங்கள் உயரத்திற்கு இலக்கு எடை",
    profileAgeBandHint: "உங்கள் வயது பதிவை அடிப்படையாகக் கொண்டது.",
    profileTargetBmiHint: "வயது பகுதியின் நடுப்புள்ளி BMI.",
    profileTargetWeightHint: "உங்கள் உயரத்தை வைத்து கணக்கிடப்பட்டது.",
    profileGoalPlan: "இலக்கு திட்டம்",
    profileGoalHint: "உங்கள் இலக்கும் செயல்பாட்டு நிலையையும் தேர்ந்தெடுக்கவும்.",
    profileGoalLoss: "எடை குறைப்பு",
    profileGoalMaintain: "எடை நிலை",
    profileGoalGain: "எடை அதிகரிப்பு",
    profileActivitySedentary: "செயற்பாடு குறைவு",
    profileActivityLight: "லேசான பயிற்சி (1-3 நாட்கள்)",
    profileActivityModerate: "மிதமான (3-5 நாட்கள்)",
    profileActivityActive: "செயலில் (6-7 நாட்கள்)",
    profileActivityVeryActive: "மிகவும் செயலில் (ஒருநாளில் 2 முறை)",
    profileBmr: "BMR",
    profileTdee: "TDEE",
    profileTargetCalories: "இலக்கு கலோரி",
    profileWaterTarget: "தினசரி தண்ணீர் இலக்கு",
    profileWorkoutGuidance: "வொர்க்அவுட் வழிகாட்டல்",
    reminderTitle: "வொர்க்அவுட் ரிமைண்டர்",
    reminderSubtitle: "நேரமும் நாட்களையும் தேர்வு செய்யுங்கள்.",
    reminderEnable: "ரிமைண்டர் இயக்கு",
    reminderChannelLabel: "அனுப்பு வழிகள்",
    reminderChannelsHint: "குறைந்தது ஒரு channel தேர்வு செய்யவும். SMS-க்கு Country code-உடன் phone number வேண்டும்.",
    reminderChannelEmail: "மின்னஞ்சல்",
    reminderChannelSms: "SMS",
    reminderPhone: "SMS மொபைல் எண் (+CountryCode)",
    reminderCountryCode: "நாட்டு குறியீடு",
    reminderPhoneNumber: "மொபைல் எண்",
    reminderPhoneHint: "உதா: +919876543210",
    reminderPhoneInvalid: "தேர்ந்த நாட்டுக்கான சரியான எண்ணை உள்ளிடவும்.",
    reminderStartDate: "எது முதல் அனுப்ப வேண்டும்",
    reminderStartDateHint: "இந்த தேதிக்கு முன் ரிமைண்டர் அனுப்பாது.",
    reminderQuietHours: "அமைதியான நேரம்",
    reminderQuietHoursHint: "இந்த நேர எல்லைகளில் ரிமைண்டர் அனுப்பப்படாது.",
    reminderQuietStart: "அமைதி தொடக்கம்",
    reminderQuietEnd: "அமைதி முடிவு",
    reminderSave: "ரிமைண்டரை சேமிக்கவும்",
    reminderSaved: "ரிமைண்டர் சேமிக்கப்பட்டது",
    reminderFailed: "ரிமைண்டரை சேமிக்க முடியவில்லை",
    reminderValidation: "நாட்கள், நேரம், குறைந்தது ஒரு channel தேர்வு செய்யவும்.",
    reminderSmsValidation: "SMS-க்கு சரியான phone number நிரப்பவும்.",
    reminderQuietValidation: "அமைதி நேரத்துக்கு தொடக்கமும் முடிவும் வேண்டியது அவசியம்.",
    weeklyMealTitle: "வாராந்திர உணவு திட்டம்",
    weeklyMealSubtitle: "வாரத்தில் குறைந்த முறை மறுபடி வரும் வகையில்.",
    "meal.breakfast": "காலை உணவு",
    "meal.lunch": "மதிய உணவு",
    "meal.snack": "ஸ்நாக்",
    "meal.dinner": "இரவு உணவு",
    mealColFood: "உணவு",
    mealColAmount: "அளவு",
    mealColCalories: "கலோரி",
    dayMon: "திங்கள்",
    dayTue: "செவ்வாய்",
    dayWed: "புதன்",
    dayThu: "வியாழன்",
    dayFri: "வெள்ளி",
    daySat: "சனி",
    daySun: "ஞாயிறு",
    gainFoodWaterHint: "தண்ணீர் இலக்கு: தினமும் {amount} ml.",
    gainFoodRice: "சாதம் (1 கப்)",
    gainFoodOats: "ஓட்ஸ் (40g)",
    gainFoodEggs: "முட்டை (2)",
    gainFoodChicken: "சிக்கன் (150g)",
    gainFoodPaneer: "பனீர் (100g)",
    gainFoodNuts: "கலந்த நட்ஸ் (30g)",
    gainFoodBanana: "வாழை (1)",
    gainFoodMilk: "பால் (250ml)",
    gainFoodVeg: "காய்கறிகள் (1 கப்)",
    gainFoodIdli: "இட்லி (3)",
    gainFoodSambar: "சாம்பார் (1 கப்)",
    gainFoodPoha: "போஹா (1 பவுல்)",
    gainFoodUpma: "உப்புமா (1 பவுல்)",
    gainFoodDosa: "தோசை (2)",
    gainFoodRoti: "ரொட்டி (2)",
    gainFoodFish: "மீன் (150g)",
    gainFoodRajma: "ராஜ்மா (1 கப்)",
    gainFoodYogurt: "தயிர் (200ml)",
    gainFoodFruitBowl: "பழக் கிண்ணம் (1)",
    gainFoodPeanutButter: "பீனட் பட்டர் (2 tbsp)",
    gainFoodBread: "முழுதானிய பிரெட் (2)",
    "reminderDay.0": "ஞா",
    "reminderDay.1": "தி",
    "reminderDay.2": "செ",
    "reminderDay.3": "பு",
    "reminderDay.4": "வி",
    "reminderDay.5": "வெ",
    "reminderDay.6": "ச",
    formFoodItem: "உணவு பெயர்",
    formCalories: "கலோரி",
    formDate: "தேதி",
    formAddMeal: "உணவு சேர்",
    formFoodSuggestions: "நீங்கள் கைமுறையாக டைப் செய்யலாம் அல்லது suggestions-லிருந்து தேர்வு செய்யலாம்.",
    formWaterMl: "தண்ணீர் (ml)",
    formAddWater: "தண்ணீர் சேர்",
    formWorkoutType: "வொர்க்அவுட் வகை",
    formWorkoutMinutes: "நிமிடங்கள்",
    formAddWorkout: "வொர்க்அவுட் சேர்",
    formHeartRate: "இதய துடிப்பு (bpm)",
    formAddHeartRate: "துடிப்பு சேர்",
    suggestionIdli: "இட்லி",
    suggestionDosa: "தோசை",
    suggestionRice: "சாதம்",
    suggestionChicken: "சிக்கன்",
    suggestionPaneer: "பனீர்",
    suggestionEggs: "முட்டை",
    suggestionOats: "ஓட்ஸ்",
    suggestionFruit: "பழக் கிண்ணம்",
    suggestionMilk: "பால்",
    suggestionYogurt: "தயிர்",
    suggestionNuts: "கலந்த நட்ஸ்",
    suggestionPoha: "போஹா",
    suggestionUpma: "உப்புமா",
    suggestionSambar: "சாம்பார்",
    suggestionFish: "மீன்",
    suggestionRajma: "ராஜ்மா",
    suggestionSalad: "சலாட்",
    categoryCardio: "கார்டியோ",
    categoryStrength: "ஸ்ட்ரெங்க்த்",
    categoryYoga: "யோகா",
    categoryHIIT: "HIIT",
    categoryMobility: "மொபிலிட்டி",
    categoryOther: "மற்றவை",
    loading: "ஏற்றப்படுகிறது...",
    adminDelete: "நீக்கு",
    profileBmi: "BMI",
    profileGenderMale: "ஆண்",
    profileGenderFemale: "பெண்",
    profileGenderOther: "மற்றது",
    planWeekA: "வார திட்டம் A",
    planWeekB: "வார திட்டம் B",
    planLossFocusA: "3 வலு பயிற்சி + 2 கார்டியோ",
    planLossSessionsA: "திங்கள் Upper, செவ் Cardio, வியா Lower, வெள்ளி Cardio, சனி Full body",
    planLossNutritionA: "மிதமான calorie deficit + அதிக புரதம் + காய்கறிகள்.",
    planLossHydrationA: "நாளெல்லாம் தண்ணீர்; இலக்கு அளவை பின்பற்றுங்கள்.",
    planLossFocusB: "4 வலு பயிற்சி + 1 HIIT",
    planLossSessionsB: "திங்கள் Upper, செவ் Lower, வியா Push, வெள்ளி Pull, சனி HIIT",
    planLossNutritionB: "Workout நேரத்தில் கார்ப், ஒவ்வொரு உணவிலும் புரதம்.",
    planLossHydrationB: "பயிற்சி நாளில் கூடுதலாக 500 ml சேர்க்கவும்.",
    planGainFocusA: "4-5 வலு பயிற்சி + 1 லேசான கார்டியோ",
    planGainSessionsA: "திங்கள் Push, செவ் Pull, வியா Legs, வெள்ளி Upper, சனி Light cardio",
    planGainNutritionA: "Calorie surplus + புரதம் + complex carbs.",
    planGainHydrationA: "இலக்கு தண்ணீர்; கனமான நாளில் 250-500 ml கூடுதலாக.",
    planGainFocusB: "Upper/Lower split (volume focus)",
    planGainSessionsB: "திங்கள் Upper, செவ் Lower, வியா Upper, வெள்ளி Lower, சனி Optional arms",
    planGainNutritionB: "4-5 சிறிய meals, healthy fats சேர்க்கவும்.",
    planGainHydrationB: "தொடர்ந்து தண்ணீர்; நீண்ட இடைவெளி தவிர்க்கவும்.",
    planGuidanceLoss:
      "வலு பயிற்சி 3-4 நாள்/வாரம் + 150-300 நிமிடங்கள் மிதமான கார்டியோ. Recovery நல்லா இருந்தா 1-2 HIIT சேர்க்கலாம்.",
    planGuidanceGain:
      "Strength 4-5 நாள்/வாரம், progressive overload முக்கியம். Cardio 1-2 நாள் மட்டும் லேசாக.",
    planGuidanceMaintain:
      "3 நாள் strength + 2-3 நாள் cardio அல்லது active recovery-யுடன் பராமரிக்கவும்.",
    maintainFoodOats: "ஓட்ஸ் (40g)",
    maintainFoodFruit: "பழம் (1)",
    maintainFoodRice: "சாதம் (1 கப்)",
    maintainFoodChicken: "சிக்கன் (150g)",
    maintainFoodVeg: "காய்கறிகள் (1 கப்)",
    maintainFoodNuts: "கலந்த நட்ஸ் (30g)",
    maintainFoodYogurt: "தயிர் (200ml)",
    maintainFoodRoti: "ரொட்டி (2)",
    maintainFoodPaneer: "பனீர் (100g)",
    maintainFoodIdli: "இட்லி (3)",
    maintainFoodSambar: "சாம்பார் (1 கப்)",
    maintainFoodFish: "மீன் (150g)",
    maintainFoodEggs: "முட்டை (2)",
    maintainFoodPoha: "போஹா (1 பவுல்)",
    maintainFoodMilk: "பால் (250ml)",
    maintainFoodRajma: "ராஜ்மா (1 கப்)",
    maintainFoodUpma: "உப்புமா (1 பவுல்)",
    maintainFoodDosa: "தோசை (2)",
    lossFoodOats: "ஓட்ஸ் (40g)",
    lossFoodFruit: "பழம் (1)",
    lossFoodRice: "சாதம் (1 கப்)",
    lossFoodChicken: "சிக்கன் (150g)",
    lossFoodVeg: "காய்கறிகள் (1 கப்)",
    lossFoodNuts: "கலந்த நட்ஸ் (30g)",
    lossFoodYogurt: "தயிர் (200ml)",
    lossFoodRoti: "ரொட்டி (2)",
    lossFoodPaneer: "பனீர் (100g)",
    lossFoodIdli: "இட்லி (3)",
    lossFoodSambar: "சாம்பார் (1 கப்)",
    lossFoodFish: "மீன் (150g)",
    lossFoodEggs: "முட்டை (2)",
    lossFoodPoha: "போஹா (1 பவுல்)",
    lossFoodMilk: "பால் (250ml)",
    lossFoodRajma: "ராஜ்மா (1 கப்)",
    lossFoodUpma: "உப்புமா (1 பவுல்)",
    lossFoodDosa: "தோசை (2)",
    assistantTitle: "கோச் சந்தை",
    assistantSubtitle: "பயிற்சி, உணவு, அல்லது ஆப் பற்றி கேளுங்கள்.",
    assistantInputPlaceholder: "உங்கள் கேள்வியை டைப் செய்யுங்கள்...",
    assistantSend: "அனுப்பு",
    assistantOpenButton: "உதவி வேணுமா?",
    assistantClose: "மூடு",
    assistantEmpty: "இன்னும் உரையாடல் இல்லை. வணக்கம் சொல்லுங்கள்!",
    assistantWelcome:
      "ஹாய்! நான் உங்கள் AI கோச். பயிற்சி திட்டம், உணவு, அல்லது SNM Health Monitor அம்சங்கள் பற்றி கேளுங்கள்.",
    assistantError: "பதில் வரவில்லை. மீண்டும் முயற்சிக்கவும்.",
    assistantThinking: "சிந்தித்து கொண்டிருக்கிறேன்..."
  }
};

const interpolate = (text, vars) => {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (_, key) => (vars[key] ?? ""));
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem("lang") || "en");

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("lang", lang);
  };

  const t = (key, vars) => {
    const dict = translations[language] || translations.en;
    const value = dict[key] || translations.en[key] || key;
    return interpolate(value, vars);
  };

  const value = useMemo(() => ({ language, setLanguage: changeLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);

